name: dart_macros
description: A powerful Dart package that brings C-style macro preprocessing capabilities to Dart.
version: 1.0.1
homepage: https://github.com/samuelkchris/dart_macros

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  source_gen: ^2.0.0
  build: ^2.4.0
  analyzer: ^7.2.0
  path: ^1.8.0
  collection: ^1.18.0

  meta: ^1.16.0
  glob: ^2.1.3
  yaml: ^3.1.3
  stack_trace: ^1.12.1
dev_dependencies:
  lints: ^5.1.1
  test: ^1.24.0
  build_runner: ^2.4.0
  build_test: ^2.2.0