name: dart_macros
description: A powerful Dart package that brings C-style macro preprocessing capabilities to Dart.
version: 0.1.0
homepage: https://github.com/samuelkchris/dart_macros

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  source_gen: ^1.4.0
  build: ^2.4.0
  analyzer: ^6.2.0
  path: ^1.8.0
  collection: ^1.18.0

dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.0
  build_runner: ^2.4.0
  build_test: ^2.2.0